export default {
  GET_PHOTOS: 'GET_PHOTOS',
  GET_COLLECTIONS: 'GET_COLLECTIONS',
  CHANGE_LOGO_ALT: 'CHANGE_LOGO_ALT',
  RESET_LOGO_ALT: 'RESET_LOGO_ALT',
  ADD_MENU_ITEM: 'ADD_MENU_ITEM',
  REMOVE_MENU_ITEM: 'REMOVE_MENU_ITEM'
}